# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0053c6e9438891b01a1097efde39216481cb70bb204007e9e27a4920962e64edcc2970d409ca815d3b9f528ba01e29a26892f8964ff00ceb4603c197a5acd6c5

test:
  secret_key_base: 23d23c009bb5097a01d7083bc0417a758f3d5424886d64742eaeefe25e287e1f7ba3b44b7bf8977431db7b463ba20e545b26a881cb79fe011dce9828e000c948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
